apiVersion: v1
kind: Service
metadata:
  name: beggarclothes-admin-service
spec:
  selector:
    app: beggarclothes-admin
  ports:
  - port: 9098
    protocol: "TCP"
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beggarclothes-admin-deployment
spec:
  selector:
    matchLabels:
      app: beggarclothes-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: beggarclothes-admin
    spec:
      containers:
      - name: nginx
        image: "batteryho/beggarclothes-admin:latest"
        imagePullPolicy: Always
        ports:
        - containerPort: 80